namespace iTunesDB.Net.Enumerations
{
    public enum MhodTypes
    {
        Title = 1,
        Location = 2,
        Album = 3,
        Artist = 4,
        Genre = 5,
        FileType = 6,
        EqSetting = 7,
        Comment = 8,
        Category = 9,
        Composer = 12,
        Grouping = 13,
        Description = 14,
        PodcastEnclosureUrl = 15,
        PodcastRssUrl = 16,
        ChapterData = 17,
        Subtitle = 18,
        TvShow = 19,
        TvShowEpisodeNumber = 20,
        TvNetwork = 21,
        AlbumArtist = 22,
        SortByArtistName = 23,
        Keywords = 24,
        LocaleForTvShow = 25,
        SortByTitle = 27,
        SortByAlbum = 28,
        SortByAlbumArtist = 29,
        SortByComposer = 30,
        SortByTvShow = 31,
        Unknown = 32,
        SmartPlayListSettings = 50,
        SmartPlayListRules = 51,
        LibraryPlayListIndex = 52,
        LibraryPlayListJumpTable = 53,
        ColumnSizingOrPlaylistOrderIndicator = 100,
        AlbumListAlbum = 200,
        AlbumListArtist = 201,
        AlbumListSortByArtist = 202,
        AlbumListPodcastUrl = 203,
        AlbumListTvShow = 204,
        AlbumListArtistMhii = 300
    }
}
